### ISSUE TITLE
[MS21] Native Compilation Support #1

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#2830]
This is the first milestone devoted to fixing GraalVM support in Log4j.

## Tasks

- [x] Fix GraalVM support in `log4j-api` (#2392),
- [x] Automatically check GraalVM compatibility for each Log4j API implementation (https://github.com/apache/logging-log4j-samples/commit/94c819ecdef430640b8a5367eacfdffca9cd5dc3)
- [x] Release Log4j API 2.24.0
- [x] Create and validate a plan to introduce GraalVM support in Log4j Core and the remaining modules. This is discussed in #2364.

**Comment by ppkarwasz** [comment]
@vy,

I added the documentation task to #2831.

**Comment by ppkarwasz** [comment]
A set of integration tests has been scheduled daily. See [CI run 10638659451](https://github.com/apache/logging-log4j-samples/actions/runs/10638659451) for example.

Note the the `simple` test case will fail until #2908 is merged.

**Comment by ppkarwasz** [comment]
The [CI run 10647359122](https://github.com/apache/logging-log4j-samples/actions/runs/10647359122) gives a green light for a `2.24.0` release.

**Comment by ppkarwasz** [comment]
The [2.24.0 release](https://github.com/apache/logging-log4j2/releases/tag/rel%2F2.24.0) has just shipped with GraalVM support out-of-the box in the API

Regarding GraalVM support in the rest of Log4j, the plan is as follows:

1. Extend `log4j-docgen` to be able to generate GraalVM reflection metadata.
2. Publish the reachability metadata on [oracle/graalvm-reachability-metadata](https://github.com/oracle/graalvm-reachability-metadata) with **all** the plugins.

**Comment by vy** [comment]
> Extend `log4j-docgen` to be able to generate GraalVM reflection metadata.

Why do we use `log4j-docgen` but not `log4j-plugins` instead to generate this metadata?

**Comment by ppkarwasz** [comment]
I guess we can extend `log4j-plugin-processor` to generate code for each configuration attribute, this way **no** reflection metadata is necessary. WDYT?

**Comment by grobmeier** [comment]
Thanks for the hard work
