### ISSUE TITLE
 [MS23] Native Compilation Support #3

### ISSUE THREAD

**Issue by ppkarwasz** [apache/logging-log4j2#2832]
This is the third milestone, after #2831, devoted to fixing GraalVM support in Log4j.

## Tasks

- [x] <s>Fix GraalVM support in `log4j-json-template-layout`.</s>

### Additional tasks

Since the main was achieved in the previous #2831 milestone, we profit from the occasion to complete the following tasks:

- [x] #3071

**Comment by ppkarwasz** [comment]
To ensure that each Log4j release will be compatible with Android and all the other platforms we support (JPMS/JLink, GraalVM, OSGi) the following steps were taken:

- [ ] Fix the currently known issues on Android: #3071.
- [ ] Add an example of Android application that uses Log4j: apache/logging-log4j-samples#196
- [ ] Automatize the build of the Android application on the CI with some native tests: apache/logging-log4j-samples#198
- [ ] Run all the tests for JLink, Android and GraalVM on a regular basis: apache/logging-log4j-samples#199
- [ ] Require a successful run of the integration tests, before a release vote is submitted: apache/logging-parent#269

**Comment by ppkarwasz** [comment]
In #3105, https://github.com/apache/logging-parent/pull/270 and https://github.com/apache/logging-parent/pull/271 we automate further the integration tests workflow: now no Release Manager can forget about it, because it starts automatically.

**Comment by grobmeier** [comment]
Thanks for the work!
